apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-13T14:54:45Z"
  generateName: api-6cb786cb99-
  labels:
    app: api
    pod-template-hash: 6cb786cb99
  name: api-6cb786cb99-mffx4
  namespace: argocd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: api-6cb786cb99
    uid: 987756f5-4cb5-4a0f-b426-c54706f3f12b
  resourceVersion: "30288"
  uid: a332861d-c658-4017-bb6b-1ae369584cc2
spec:
  containers:
  - env:
    - name: QUOTES_API
      valueFrom:
        configMapKeyRef:
          key: QUOTES_API
          name: api-cm-7h2k2d822g
    image: aakniazi/apigateway
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: http://api-service:3000/api/status
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: api
    ports:
    - containerPort: 3000
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: http://api-service:3000/api/status
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6wz59
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - -c
    - until nc -z quotes-service 5000; do sleep 1; done
    image: busybox
    imagePullPolicy: Always
    name: wait-for-quotes-service
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6wz59
      readOnly: true
  nodeName: minikube-m03
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-6wz59
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-13T14:54:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-13T14:54:59Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-13T14:54:59Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-13T14:54:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2c3d1dc4ae87c84d3770aac3dfff351d0e1c027cec4dbcad557d6294245cdccf
    image: aakniazi/apigateway:latest
    imageID: docker-pullable://aakniazi/apigateway@sha256:8f0cdbfe967075edb266090c419525ff648c6f4a83c79df9a2ed4b1d2afd6212
    lastState: {}
    name: api
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-13T14:54:58Z"
  hostIP: 192.168.59.103
  initContainerStatuses:
  - containerID: docker://d36d69dee7df5c17e9c82cb5c069d591e9c026a4ba5d2d132de1638e259a65fb
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79
    lastState: {}
    name: wait-for-quotes-service
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://d36d69dee7df5c17e9c82cb5c069d591e9c026a4ba5d2d132de1638e259a65fb
        exitCode: 0
        finishedAt: "2023-10-13T14:54:53Z"
        reason: Completed
        startedAt: "2023-10-13T14:54:52Z"
  phase: Running
  podIP: 10.244.2.33
  podIPs:
  - ip: 10.244.2.33
  qosClass: Burstable
  startTime: "2023-10-13T14:54:45Z"
