# quotes-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: test-proj
spec:
  selector:
    app: quotes
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000