---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-proj
  name: read-only-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-only-role-binding
  namespace: test-proj
subjects:
- kind: User  
  name: aliabid
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-proj
  name: read-write-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-write-role-binding
  namespace: test-proj
subjects:
- kind: User
  name: aliabid
roleRef:
  kind: Role
  name: read-write-role
  apiGroup: rbac.authorization.k8s.io

